# [[file:../../init.org::*Github Actions][Github Actions:1]]
# This workflow will do a clean install of dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/

name: Emacs Loads Successfully

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          # The version of Emacs to install, e.g. "24.3", or "snapshot" for a recent development version.
          version: 27.1 # optional

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.

      - name: where am I and what is here
        run: |
          pwd
          ls

      - name: Local Doom
        run: |
          cp -ar ~/work/.doom.d/.doom.d/ ~/.doom.d

      - name: Get Doom
        run: |
          # mv ~/.emacs.d/ ~/.emacs.d.old/ ## emacs is not initialized yet
          git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
          ~/.emacs.d/bin/doom install --no-env --no-fonts

      - name: Sync local Doom
        run: ~/.emacs.d/bin/doom sync

      - name: Attempting startup...
        run: time emacs -nw
